name: full_coverage
description: A package script for allowing coverage test tool to see all Dart files.
version: 0.0.3
homepage: https://github.com/Flutterando/full_coverage

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  args: ^2.3.0
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  full_coverage:
